# Generated by Django 5.2.3 on 2025-06-29 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_band', models.CharField(max_length=50)),
                ('issue_size', models.CharField(max_length=100)),
                ('issue_type', models.CharField(max_length=100)),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('ipo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('listing_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cmp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current Market Price')),
                ('current_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipos', to='ipo.company')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhp', models.FileField(blank=True, null=True, upload_to='docs/rhp/')),
                ('drhp', models.FileField(blank=True, null=True, upload_to='docs/drhp/')),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ipo.ipo')),
            ],
        ),
    ]
